services:
  - type: web
    name: growv2-api
    env: python
    plan: starter
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    branch: main